biosys/apps/main/api/urls.py
from __future__ import absolute_import, unicode_literals, print_function, division

from django.conf.urls import url
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from djoser import views as djoser_views

from main.api import views as api_views

router = routers.DefaultRouter()
router.register(r'users?', api_views.UserViewSet, 'user')
router.register(r'programs?', api_views.ProgramViewSet, 'program')
router.register(r'projects?', api_views.ProjectViewSet, 'project')
router.register(r'sites?', api_views.SiteViewSet, 'site')
router.register(r'datasets?', api_views.DatasetViewSet, 'dataset')
router.register(r'records?', api_views.RecordViewSet, 'record')
router.register(r'media', api_views.MediaViewSet, 'media')
router.register(r'project-media', api_views.ProjectMediaViewSet, 'project-media')
router.register(r'dataset-media', api_views.DatasetMediaViewSet, 'dataset-media')


url_patterns = [
    url(r'auth-token/', obtain_auth_token, name="auth-token"),
    url(r'projects?/(?P<pk>\d+)/sites/?', api_views.ProjectSitesView.as_view(), name='project-sites'),  # bulk sites
    url(r'projects?/(?P<pk>\d+)/upload-sites/?', api_views.ProjectSitesUploadView.as_view(),
        name='upload-sites'),  # file upload for sites
    url(r'datasets?/(?P<pk>\d+)/records/?', api_views.DatasetRecordsView.as_view(), name='dataset-records'),
    # upload data files
    url(r'datasets?/(?P<pk>\d+)/upload-records/?', api_views.DatasetUploadRecordsView.as_view(),
        name='dataset-upload'),
    url(r'statistics/?', api_views.StatisticsView.as_view(), name="statistics"),
    url(r'whoami/?', api_views.WhoamiView.as_view(), name="whoami"),
    url(r'species/?', api_views.SpeciesView.as_view(), name="species"),
    url(r'logout/?', api_views.LogoutView.as_view(), name="logout"),
    # utils
    url(r'utils/geometry-to-data/dataset/(?P<pk>\d+)/?',
        api_views.GeoConvertView.as_view(output='data'),
        name="geometry-to-data"
        ),
    url(r'utils/data-to-geometry/dataset/(?P<pk>\d+)/?',
        api_views.GeoConvertView.as_view(output='geometry'),
        name="data-to-geometry"
        ),
    url(r'utils/infer-dataset/?', api_views.InferDatasetView.as_view(), name='infer-dataset'),
    url(r'^password/?$', djoser_views.SetPasswordView.as_view(), name='set-password'),
    url(
        r'^password/reset/?$',
        djoser_views.PasswordResetView.as_view(),
        name='password-reset'
    ),
    url(
        r'^password/reset/confirm/?$',
        djoser_views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm'
    ),
]

app_name = 'api'
urls = router.urls + url_patterns

biosys/apps/main/urls.py
from django.urls import re_path

from main import views as main_views

download_urlpatterns = ([
    re_path(r'templates/site/lat-long/?',
        main_views.SiteTemplateView.as_view(model='lat_long'),
        name="site-template-lat-long"
        ),
    re_path(r'templates/site/easting-northing/?',
        main_views.SiteTemplateView.as_view(model='easting_northing'),
        name="site-template-easting-northing"
        ),
], 'download')

biosys/apps/publish/urls.py
from django.urls import re_path

from apps.publish.views import data_view, export

publish_urlpatterns = ([
    re_path(r'^$', data_view.DataView.as_view(), name='data_view'),
    re_path(r'^data/(?P<pk>\d+)/?$', data_view.JSONDataTableView.as_view(), name='data_json'),
    re_path(r'^export/(?P<pk>\d+)/?$', export.ExportDataSetView.as_view(), name='data_export'),
    re_path(r'^export-template/(?P<pk>\d+)/?$', export.ExportTemplateView.as_view(), name='data_export_template')
], 'publish')

biosys/urls.py
from __future__ import absolute_import, unicode_literals, print_function, division

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect
from django.urls import re_path
from django.views.generic import TemplateView
from rest_framework.authentication import BasicAuthentication, SessionAuthentication, TokenAuthentication
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from main.api.permissions import CanViewSwagger
from main.views import DashboardView
from main.api.urls import urls as api_endpoints
from main.urls import download_urlpatterns
from publish.urls import publish_urlpatterns


def home_view_selection_view(request):
    if request.user.is_authenticated:
        return redirect('api/explorer')
    else:
        return redirect('login')


def admin_view_selection_view(request):
    if request.user.is_superuser:
        return admin.site.index(request)
    elif request.user.is_authenticated:
        return redirect('dashboard')
    else:
        return redirect('login')


web_urls = [
    # Authentication URLs
    re_path(r'^logout/$', LogoutView.as_view(), {'next_page': '/login/'}, name='logout'),
    # re_path(r'^login/$', auth_views.login),
    re_path('^', include('django.contrib.auth.urls')),
    # Application URLs
    re_path(r'^download/', include(download_urlpatterns, namespace='download')),
    re_path(r'^admin/logout/$', LogoutView.as_view(), {'next_page': '/'}),
    # use a function to determine where admin/ will resolve to, based on the user
    re_path(r'^admin/$', admin_view_selection_view),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^publish/', include(publish_urlpatterns, namespace='publish')),
    re_path(r'^$', home_view_selection_view, name='home'),
    re_path(r'^dashboard/', login_required(DashboardView.as_view()), name='dashboard'),
    re_path(r'^about/', TemplateView.as_view(template_name='main/about.html'), name='about'),

    # legacy
    re_path(r'^grappelli/', include('grappelli.urls')),  # Grappelli URLS
]

api_urls = [
    re_path(r'^api/', include((api_endpoints, 'api'))),
]

sso_api_urls = [
    re_path(r'^sso-api/', include((api_endpoints, 'sso-api'))),
]

media_urls = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schema_view = get_schema_view(
    openapi.Info(
        title="Biosys API",
        default_version='v1',
        description="Biosys API Documentation",
    ),
    public=True,
    patterns=api_urls,
    authentication_classes=(SessionAuthentication, BasicAuthentication, TokenAuthentication),
    permission_classes=(CanViewSwagger,)
)

api_doc_urls = [
    re_path(r'^api/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=None), name='doc-json'),
    re_path(r'^api/explorer/$', schema_view.with_ui('swagger', cache_timeout=None), name='doc-swagger'),
    re_path(r'^api/redoc/$', schema_view.with_ui('redoc', cache_timeout=None), name='doc-redoc'),
]

urlpatterns = web_urls + api_urls + api_doc_urls + media_urls + sso_api_urls

biosys/apps/main/models.py
from __future__ import absolute_import, unicode_literals, print_function, division

import logging
from os import path

from datapackage import validate as datapackage_validate
from datapackage import exceptions as datapackage_exceptions
from tableschema import validate as tableschema_validate
from tableschema import exceptions as tableschema_exceptions
from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.gis.db.models import Extent
from django.db.models import JSONField
from django.core.exceptions import ValidationError
from django.utils.text import Truncator
from django.db.models.query_utils import Q
from timezone_field import TimeZoneField

from main.constants import DATUM_CHOICES, MODEL_SRID
from main.utils_auth import is_admin
from main.utils_data_package import GenericSchema, ObservationSchema, SpeciesObservationSchema

logger = logging.getLogger(__name__)


class Program(models.Model):
    name = models.CharField(max_length=300, null=False, blank=False, unique=True,
                            verbose_name="Name", help_text="Enter a name for the program (required).")
    code = models.CharField(max_length=30, null=True, blank=True,
                            verbose_name="Code",
                            help_text="Provide a brief code or acronym for this program.")

    description = models.TextField(null=True, blank=True,
                                   verbose_name="Description", help_text="")

    data_engineers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        help_text="Users that can create/update projects and dataset schema within this program."
    )

    def is_data_engineer(self, user):
        return user in self.data_engineers.all()

    # API permissions
    @staticmethod
    def has_read_permission(request):
        return True

    def has_object_read_permission(self, request):
        return True

    @staticmethod
    def has_metadata_permission(request):
        return True

    def has_object_metadata_permission(self, request):
        return True

    @staticmethod
    def has_create_permission(request):
        return is_admin(request.user)

    @staticmethod
    def has_update_permission(request):
        return is_admin(request.user)

    @staticmethod
    def has_object_update_permission(request):
        return is_admin(request.user)

    @staticmethod
    def has_destroy_permission(request):
        return is_admin(request.user)

    @staticmethod
    def has_object_destroy_permission(request):
        return is_admin(request.user)

    def __str__(self):
        return self.name


class Project(models.Model):
    DEFAULT_TIMEZONE = settings.TIME_ZONE

    program = models.ForeignKey(Program, blank=False, null=False, on_delete=models.CASCADE,
                                help_text="The program this project belongs to.")

    name = models.CharField(max_length=300, null=False, blank=False, unique=True,
                            verbose_name="Name", help_text="Enter a name for the project (required).")
    code = models.CharField(max_length=30, null=True, blank=True,
                            verbose_name="Code",
                            help_text="Provide a brief code or acronym for this project. "
                                      "This code could be used for prefixing site codes.")

    datum = models.IntegerField(null=True, blank=True, choices=DATUM_CHOICES, default=MODEL_SRID,
                                verbose_name="Default Datum",
                                help_text="The datum all locations will be assumed to have unless otherwise specified.")

    timezone = TimeZoneField(blank=True, default=DEFAULT_TIMEZONE,
                             help_text="The Timezone of your project e.g 'Australia/Perth.")

    attributes = JSONField(null=True, blank=True,
                           help_text="Define here all specific attributes of your project in the form of json "
                                     "'attribute name': 'attribute value")
    description = models.TextField(null=True, blank=True,
                                   verbose_name="Description", help_text="")

    geometry = models.GeometryField(srid=MODEL_SRID, spatial_index=True, null=True, blank=True, editable=True,
                                    verbose_name="Extent",
                                    help_text="The boundary of your project (not required). "
                                              "Can also be calculated from the extents of the project sites")
    site_data_package = JSONField(null=True, blank=True,
                                  verbose_name='Site attributes schema',
                                  help_text='Define here the attributes that all your sites will share. '
                                            'This allows validation when importing sites.')

    custodians = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=False,
                                        help_text="Users that have write/upload access to the data of this project.")

    def is_custodian(self, user):
        return user in self.custodians.all()

    def is_data_engineer(self, user):
        return self.program.is_data_engineer(user)

    # API permissions
    @staticmethod
    def has_read_permission(request):
        return True

    def has_object_read_permission(self, request):
        return True

    @staticmethod
    def has_metadata_permission(request):
        return True

    def has_object_metadata_permission(self, request):
        return True

    @staticmethod
    def has_create_permission(request):
        """
        Admin or data_engineer of the program the project would belong to.
        Check that the user is a data_engineer of the program pk passed in the POST data.
        :param request:
        :return:
        """
        result = False
        if is_admin(request.user):
            result = True
        elif 'program' in request.data:
            program = Program.objects.filter(pk=request.data['program']).first()
            result = program is not None and program.is_data_engineer(request.user)
        return result

    @staticmethod
    def has_update_permission(request):
        """
        The update is managed at the object level (see below)
        :param request:
        :return:
        """
        return True

    def has_object_update_permission(self, request):
        """
        Admin or program data_engineer or project custodian
        :param request:
        :return:
        """
        user = request.user
        return is_admin(user) or self.program.is_data_engineer(user)

    @staticmethod
    def has_destroy_permission(request):
        return True

    def has_object_destroy_permission(self, request):
        """
        Admin or program data_engineer or project custodian
        :param request:
        :return:
        """
        user = request.user
        return is_admin(user) or self.program.is_data_engineer(user)

    @property
    def centroid(self):
        return self.geometry.centroid if self.geometry else None

    @property
    def extent(self):
        return self.geometry.extent if self.geometry else None

    @property
    def dataset_count(self):
        return self.projects.count()

    @property
    def site_count(self):
        return self.site_set.count()

    @property
    def record_count(self):
        return Record.objects.filter(dataset__project=self).count()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Site(models.Model):
    project = models.ForeignKey('Project', null=False, blank=False,
                                verbose_name="Project", help_text="Select the project this site is part of (required)",
                                on_delete=models.CASCADE)
    name = models.CharField(max_length=150, blank=True,
                            verbose_name="Name",
                            help_text="Enter a more descriptive name for this site, if one exists.")
    code = models.CharField(max_length=100, null=False, blank=False,
                            verbose_name="Code",
                            help_text="Local site code must be unique to this project. e.g. LCI123 (required)")
    geometry = models.GeometryField(srid=MODEL_SRID, spatial_index=True, null=True, blank=True, editable=True,
                                    verbose_name="Location", help_text="")
    description = models.TextField(null=True, blank=True,
                                   verbose_name="Description", help_text="")
    attributes = JSONField(null=True, blank=True)

    def is_custodian(self, user):
        return self.project.is_custodian(user)

    def is_data_engineer(self, user):
        return self.project.is_data_engineer(user)

    # API permissions
    @staticmethod
    def has_read_permission(request):
        return True

    def has_object_read_permission(self, request):
        return True

    @staticmethod
    def has_metadata_permission(request):
        return True

    def has_object_metadata_permission(self, request):
        return True

    @staticmethod
    def has_create_permission(request):
        """
        Custodian and admin and data engineer
        Check that the user is a custodian of the project pk passed in the POST data.
        :param request:
        :return:
        """
        result = False
        user = request.user
        if is_admin(user):
            result = True
        elif 'project' in request.data:
            project = Project.objects.filter(pk=request.data['project']).first()
            result = project is not None and project.is_custodian(user) or project.is_data_engineer(user)
        return result

    @staticmethod
    def has_update_permission(request):
        """
        The update is managed at the object level (see below)
        :param request:
        :return:
        """
        return True

biosys/apps/main/templates/main/about.html
{% extends 'base.html' %}

{% load admin_urls %}

{% load static %}

{% block extra_style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block page_content_inner %}
    <div class="row">
        <div class="col-xs-12">
            <h2>About BioSys</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10">
            <p>BioSys – the Western Australian Biological Survey Database – is a web-based repository for the
                Department’s biological survey data.
                The system at Version 1.0 is currently a proof-of-concept,
                funded by the <a
                        href="http://www.dpaw.wa.gov.au/management/kimberley-strategy/conserving-the-unique-kimberley-environment/164-the-landscape-conservation-initiative">Kimberley
                    Landscape Conservation Initiative (LCI)</a>, and supporting that initiative’s immediate data
                requirements.
            </p>

            <p>
                Biological survey databases typically manage highly complex and structured data.
                In this initial version we have implemented data fields and workflow to specifically support the
                Kimberley LCI.
                In future versions, resources permitting, BioSys will be extended to support a much broader range of
                ecological data types and sampling protocols, including localised and regional survey snapshots.
            </p>

            <p>
                BioSys runs in a web browser within the Department’s internal network.
                Data is currently uploaded to the system via supplied spreadsheet templates, permitting offline data
                entry.
                Published BioSys data can be downloaded by any authorised staff member via their normal login. Data will
                also be warehoused in NatureMap, subject to custodial approval.
            </p>
        </div>
        <div class="col-xs-2">
            <img src="{% static 'img/frog-small.jpg' %}"  class="img-responsive">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h2>Acknowledgements</h2>

            <p>
                BioSys was developed at the instigation of the Director, Science and Conservation Division (SCD) using
                LCI funding.
                It was a key deliverable of the Office of Information Management’s (OIM) Knowledge Management
                Initiative, a highly successful joint venture between SCD, OIM and other sections of the Department.
                Both SCD and OIM contributed significant in-kind resources to this project, including project management
                and user liaison. Gaia Resources and OIM provided system development.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h2>Feedback</h2>

            <p>
                Your feedback and suggestions are welcome.
                For queries regarding BioSys aims, objectives and future directions, contact SCD’s <a
                    href="mailto:paul.gioia@dbca.wa.gov.au"> Ecoinformatics Unit Manager</a>.
                For access to data, or technical queries contact the <a href="mailto:biosys@dbca.wa.gov.au">system
                custodian.</a>
            </p>
        </div>
    </div>
{% endblock %}

biosys/apps/main/templates/main/dashboard.html
{% extends 'base.html' %}
{% load admin_urls %}
{% load static %}

{% block extra_style %}
{{ block.super }}
	<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block page_content_inner %}
<div class="row">
    <div class="col-xs-12">
	    <div class="page-header">
	    	<h1 style="text-align:center">Welcome to BioSys</h1>
	    </div>
	    <div class="row">
            {% if not readonly_user %}
	    	<a href="{% url 'admin:main_project_changelist' %}">
		  		<div class="col-md-3">
		    		<div class="thumbnail">
		      			<img src="{% static 'img/project.jpg' %}" alt="project">
			      		<div class="caption">
			        		<h3>Projects</h3>
		      			</div>
		    		</div>
		  		</div>
	  		</a>
	    	<a href="{% url 'admin:main_site_changelist' %}">
		  		<div class="col-md-3">
		    		<div class="thumbnail">
		      			<img src="{% static 'img/site.jpg' %}" alt="project">
			      		<div class="caption">
			        		<h3>Sites</h3>
		      			</div>
		    		</div>
		    	</div>
	  		</a>
	    	<a href="{% url 'admin:main_dataset_changelist' %}">
		  		<div class="col-md-3">
		    		<div class="thumbnail">
		      			<img src="{% static 'img/visit.jpg' %}" alt="project">
			      		<div class="caption">
			        		<h3>Data Sets</h3>
		      			</div>
		    		</div>
		    	</div>
	  		</a>
	    	<a href="{% url 'publish:data_view' %}">
		  		<div class="col-md-3">
		    		<div class="thumbnail">
		      			<img src="{% static 'img/data.jpg' %}" alt="project">
			      		<div class="caption">
			        		<h3>Data</h3>
		      			</div>
		    		</div>
		    	</div>
	  		</a>
            {% else %}
	    	<a href="{% url 'publish:data_view' %}">
            <div class="thumbnail">
                <img src="{% static 'img/data.jpg' %}" alt="project">
                <div class="caption">
                    <h3>Data</h3>
                </div>
            </div>
	  		</a>
            {% endif %}
        </div><!-- /.row -->
    </div><!-- /.col-xs-12 -->
</div><!-- /.row -->
{% endblock %}

biosys/apps/main/templates/main/data_upload.html
{% extends "main/main_change_form.html" %}
{% load i18n admin_list admin_urls %}
{% load static %}
{% load bootstrap3 %}

{% block extrastyle %}
    <link href="{% static 'css/biosys.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block messages %}
    {% if messages %}
        <ul class="grp-messagelist">
            <!-- NOTE: no message|capfirst by purpose, because it does not work in some languages -->
            {% for message in messages %}
                <li{% if message.tags %} class="grp-{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}


{% block content %}
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        <div>
            {% if form.errors %}
                <p class="errornote">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                        {% trans "Please correct the errors below." %}{% endif %}
                </p>
            {% endif %}

            {% block field_sets %}
                <fieldset class="module aligned {{ fieldset.classes }}">
                {% if fieldset.name %}<h2>{{ fieldset.name }}</h2>{% endif %}
                {% if fieldset.description %}
                    <div class="description">{{ fieldset.description|safe }}</div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-row{% if field.errors %} errors{% endif %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.field.help_text %}
                            <p class="help">{{ field.field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                </fieldset>
            {% endblock %}
        </div>
        <div class="submit-row vertical-buffer">
            <input type="submit" value="{% trans 'Submit' %}" class="default" name="_save"/>
            <input type="submit" value="{% trans 'Cancel' %}" name="_cancel"/>
        </div>
    </form>
{% endblock %}

biosys/apps/main/templates/main/dataset_change_form.html
{% extends "main/main_change_form.html" %}

{% block object-tools-items %}
    {% if not readonly_user %}
        <li><a href="{% url 'publish:data_export_template' original.pk %}">Download Template</a></li>
        {{ block.super }}
    {% endif %}
{% endblock %}

biosys/apps/main/templates/main/main_change_form.html
{% extends "admin/change_form.html" %}
{% block messages %}
    {% if messages %}
        <ul class="grp-messagelist">
            <!-- NOTE: no message|capfirst by purpose, because it does not work in some languages -->
            {% for message in messages %}
                <li{% if message.tags %} class="grp-{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block object-tools-items %}
    {% if not readonly_user %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block submit_buttons_top %}
    {% if not readonly_user %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block submit_buttons_bottom %}
    {% if not readonly_user %}
        {{ block.super }}
    {% endif %}
{% endblock %}

biosys/apps/main/templates/main/main_change_list.html
{% extends "admin/change_list.html" %}

{% block object-tools %}
    {% if not readonly_user %}
        {{ block.super }}
    {% endif %}
{% endblock %}

biosys/apps/main/templates/main/site_change_form.html
{% extends "main/main_change_form.html" %}

{% block javascripts %}
	{{ block.super }}
    <script type="text/javascript" charset="utf-8">
	    (function($) {
	        $(document).ready(function() {
	        	API_PROJECT_URL = '/api/project/';
	        	API_SITE_URL = '/api/site/';

				// change initial zoom for map if a point it set        	
	        	geodjango_geometry.map.zoomTo(6);

				$('#id_project').change(function() {
					var siteParams = {
						format: 'json',
						project__id: this.value
					};

					$.ajax({
						url: API_SITE_URL,
						type: 'get',
						data: siteParams,
						dataType: 'json'
					}).done(function () {
						$('#id_sites_to').find('option').remove();
					});

					var projectParams = {
							format: 'json',
							id: this.value
						};

					$.ajax({
						url: API_PROJECT_URL,
						type: 'get',
						data: projectParams,
						dataType: 'json'
					}).done(function (data) {
						$('#id_datum').val(data.objects[0].datum);
					});
				});
			});
	    })(grp.jQuery);
	</script>
{% endblock %}